### ISSUE TITLE
Fix save functionality to save a template

### ISSUE THREAD

**Issue by shanyas10** [bigscience-workshop/promptsource#14]
Currently, one needs to modify and save twice for template changes to reflect in templates.yaml. This needs to be fixed to save seamlessly at first go.

**Comment by arnaudstiegler** [comment]
Tried editing a an existing template, and at the first save, the templates.yaml is updated. Can you expand on the problem?

**Comment by shanyas10** [comment]
Hi! So the save works for every alternate try i.e. 1st, 3rd, 5th and so on. I found out that it's an issue inherent to streamlit (https://github.com/streamlit/streamlit/issues/1557) where the text area updates on every alternate update.

**Comment by stephenbach** [comment]
Thanks for the detective work!

I guess we could add session state back in like suggested here: https://discuss.streamlit.io/t/multi-page-app-with-session-state/3074

I think (correct me?) this problem will persist even if we go with only jinja templates and no name field as suggested by @srush because we still want to collect multiple fields: template, reference, maybe filter function (#4), maybe other metadata. So I don't see how to fix it by simplifying the design. Unless text_field works differently from text_area for some reason?

**Comment by stephenbach** [comment]
Verified that this is a problem regardless of whether using text_field or text_area. Seems inherent to any multi-input form that we want to use the output of on the next reload, so let's go back to having a session state and use the solution @shanyas10 found.

**Comment by stephenbach** [comment]
Ok, this should be fixed now. Closing this issue, but using session state in streamlit is a little tricky, so please let me know if there are remaining or new issues!
