### ISSUE TITLE
GUI APP stuck for large dataset.

### ISSUE THREAD

**Issue by sbmaruf** [bigscience-workshop/promptsource#61]
I see that for a large dataset the API stuck. Is it possible to download only a part of the data for a large dataset?

**Comment by stephenbach** [comment]
I don't think so. Since each dataset in the datasets library is loaded by an installer script, it's all or nothing. The API doesn't have any capability AFAIK to download a sample of examples.

In case it's helpful, the command line where you run streamlit will usually show a progress bar for the download. And of course, you only need to download it once. You can also browse datasets on https://huggingface.co/datasets to find one to work on before downloading them. But yeah, at the end of the day, you'll need to download it to prompt it.

I'll leave this issue open for a bit in case others have ideas.

**Comment by sbmaruf** [comment]
Thank for the explanation. 
Go ahead and close the issue when you feel the discussion is over.
