### ISSUE TITLE
[Question] What is the insight behind the strategy of choosing sampling weights?

### ISSUE THREAD

**Issue by YangDong2002** [bigscience-workshop/promptsource#642]
I am really excited about your great work! However, I want to clarify some detail that confused me in both paper and code:

In paper: (Section 5.2)

> We therefore follow the strategy used in Raffel et al. (2020) and treat any dataset with over 500’000 examples as having
500’000 / num templates examples for the purposes of sampling

In code:

https://github.com/bigscience-workshop/promptsource/blob/dc0a156159e2a5d2dbb3b10d0470e477a3d03a08/promptsource/seqio_tasks/tasks.py#L199-L202

My question is: why isn't the sampling weight defined in a more intuitive way (at least to me), treating multiple prompts as data augmentation? Can you share any insights behind this little design decision?

`cap = min(train_size, MAX_EXAMPLES_PER_DATASET // num_templates)`

**Comment by VictorSanh** [comment]
Hi, thank you for your kind words @YangDong2002.
The goal of the cap is to (very crudely) balance very big datasets with smaller datasets. Let's say you have dataset A with 1'000 training instances and dataset B with 100'000 training instances, since we are sampling uniformly, datset B would be over-sampled compared to dataset A. These cap ensure that big datasets are not over-represented.

**Comment by YangDong2002** [comment]
OK, so I won't hold on to the details too much if it is a somewhat crude way to reach a balance
