### ISSUE TITLE
template marked as original_task fails to generate test data

### ISSUE THREAD

**Issue by sbmaruf** [bigscience-workshop/promptsource#822]
Recently I came across `super_glue` `copa` prompts where templates are conditioned as following, 

```
{% if question == "cause" %} 
{{ premise }} Which may be caused by "{{ answer_choices[0] }}" or "{{ answer_choices[1] }}"? ||| {% if label != -1 %}{{ answer_choices[label] }}{%endif%}
{% endif %}
```

So lot of samples will get removed by this template. Now it is a bit annoying since calculating test score on this template may raise confusions and inaccurate outcomes. I was wondering should make sure that all the samples are generated in case of `prompt.metadata.original_task` is `True`, otherwise we assign, `prompt.metadata.original_task=False`.

**Comment by stephenbach** [comment]
Hey Maru,
We had a fair amount of debate about this, so agree that it's potentially counter-intuitive, but this is the expected behavior. From the contributing guide
```
Original Task? The checkbox should be checked if the template requires solving a task that the
underlying dataset is used to study. For example, a template that asks a question from a question
answering dataset would be an original task template, but one that asks to generate a question
for a given answer would not.
```
The reason we don't use original task in the sense you're describing is that it's very hard to certify with a check box that the results will mean what every user expects across all datasets. Therefore, it's expected that users check their templates and tasks before reporting any evaluation numbers.

Plus, on a practical note, going through and re-annotating all of these isn't really feasible. Hope this helps. Feel free to re-open if you'd like to discuss further.
